apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: techtrends
  strategy: {}
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: techtrends
          ports:
            - containerPort: {{ .Values.containerPort }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet: {{- toYaml .Values.readinessProbe | nindent 14 }}
          livenessProbe:
            httpGet: {{- toYaml .Values.livenessProbe | nindent 14 }}
