apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: techtrends
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
